# -*- coding: utf-8 -*-
"""
중간고사 예상문제 데이터
- type: "mc"(객관식) 또는 "short"(단답형)
- category: "csharp_basic" / "csharp_control" / "csharp_oop" / "unity"
- answer: 객관식은 번호(문자열), 단답형은 허용 정답 리스트
- accept: 단답형에서 대소문자/공백 무시 비교용 정답 후보
"""

QUESTIONS = [
    # ===== C# 기초 =====
    {
        "id": 1,
        "type": "mc",
        "category": "csharp_basic",
        "question": "C#의 특징에 대한 설명 중 틀린 것을 모두 고르세요. (복수답, 콤마로 구분)",
        "choices": [
            "① 간결한 프로그래밍 문법을 제공한다.",
            "② 문법 체크가 유연해서 프로그래머에게 많은 자유를 준다.",
            "③ 완전한 절차지향 언어이다.",
            "④ 멀티스레드 프로그래밍을 지원한다.",
            "⑤ 다양한 응용 프로그램을 작성할 수 있다.",
            "⑥ CLR 환경에서 개발된다.",
        ],
        "answer": "2,3",
        "multi": True,
        "explain": "② C#은 정적 타입 언어로 문법 체크가 엄격합니다. ③ C#은 객체지향 언어입니다.",
    },
    {
        "id": 2,
        "type": "mc",
        "category": "csharp_basic",
        "question": "다음 중 C#의 주석이 아닌 것을 고르세요.",
        "choices": ["① /* ~~ */", "② ##", "③ ////", "④ /** ~~ */"],
        "answer": "2",
        "explain": "C#의 주석은 //, /* */, /// (XML 문서 주석) 입니다. ##은 주석 기호가 아닙니다.",
    },
    {
        "id": 3,
        "type": "short",
        "category": "csharp_basic",
        "question": "int result=100; result=200; a=500; b=400; result=a+b; 일 때 result 값은?",
        "accept": ["900"],
        "explain": "마지막 할당 result = a + b = 500 + 400 = 900",
    },
    {
        "id": 4,
        "type": "short",
        "category": "csharp_basic",
        "question": "int a,b,c; a=100; b=200; c=b=a=300; 일 때 a의 값은?",
        "accept": ["300"],
        "explain": "대입 연산은 오른쪽에서 왼쪽으로 진행됩니다. a=300, 그 다음 b=300, c=300.",
    },
    {
        "id": 5,
        "type": "short",
        "category": "csharp_basic",
        "question": "float 변수의 올바른 초기값을 쓰세요. (예: 0, \"\", false 등)",
        "accept": ["0.0f", "0f"],
        "explain": "float 타입은 0.0f 로 초기화합니다. 0.0만 쓰면 double 타입입니다.",
    },
    {
        "id": 6,
        "type": "mc",
        "category": "csharp_basic",
        "question": "변수 이름 규칙 설명 중 가장 거리가 먼 것은?",
        "choices": [
            "① 대문자와 소문자를 구분한다.",
            "② 숫자로 시작할 수는 있으나 언더바(_)로 시작하면 안된다.",
            "③ 예약어를 사용하면 안된다.",
            "④ 대소문자를 구분한다.",
        ],
        "answer": "2",
        "explain": "반대입니다. 숫자로 시작할 수 없고, 언더바(_)로는 시작할 수 있습니다.",
    },
    {
        "id": 7,
        "type": "short",
        "category": "csharp_basic",
        "question": "10 / 3 의 결과는? (C# int 연산)",
        "accept": ["3"],
        "explain": "정수끼리의 나눗셈은 몫만 반환합니다.",
    },
    {
        "id": 8,
        "type": "short",
        "category": "csharp_basic",
        "question": "10 % 3 의 결과는?",
        "accept": ["1"],
        "explain": "%는 나머지 연산자. 10 ÷ 3 = 3 나머지 1.",
    },
    {
        "id": 9,
        "type": "short",
        "category": "csharp_basic",
        "question": "2 + 3 * 6 의 결과는?",
        "accept": ["20"],
        "explain": "곱셈이 우선. 3*6=18, 2+18=20.",
    },
    {
        "id": 10,
        "type": "mc",
        "category": "csharp_basic",
        "question": "다음 비교 연산자 중 C#에서 문법 오류가 발생하는 것은?",
        "choices": [
            "① 100 < 200",
            "② 100 > 200",
            "③ 100 <> 200",
            "④ 100 == 200",
        ],
        "answer": "3",
        "explain": "C#에서 '같지 않다'는 != 입니다. <> 는 존재하지 않습니다. (※ PDF 원본의 정답 ④는 오기로 판단됨)",
    },

    # ===== C# 제어문 =====
    {
        "id": 11,
        "type": "short",
        "category": "csharp_control",
        "question": 'int num=99; if(num>100) Debug.Log("AAA"); → 무엇이 출력되나요? (출력이 없으면 "없음")',
        "accept": ["없음", "아무것도 출력되지 않음", "nothing", "없다"],
        "explain": "99는 100보다 크지 않으므로 조건 거짓, 출력 없음.",
    },
    {
        "id": 12,
        "type": "mc",
        "category": "csharp_control",
        "question": 'int num=200; if(num<100) Debug.Log("AAA"); Debug.Log("BBB"); else Debug.Log("CCC"); → 결과는?',
        "choices": [
            "① 오류 없이 AAA BBB 출력",
            "② BBB CCC 출력",
            "③ CCC만 출력",
            "④ 컴파일 오류 발생",
        ],
        "answer": "4",
        "explain": "if문에 블록({})이 없으면 if는 한 문장만 연결됩니다. Debug.Log(\"BBB\");가 if 바깥으로 빠지면서 else와 분리되어 문법 오류가 발생합니다.",
    },
    {
        "id": 13,
        "type": "mc",
        "category": "csharp_control",
        "question": 'for(int i=1;i<3;i++) Console.Write("AAA"); Console.Write("BBB"); → 출력은?',
        "choices": [
            "① AAA BBB AAA BBB AAA BBB",
            "② AAA BBB AAA BBB",
            "③ AAA AAA AAA BBB",
            "④ AAA AAA BBB",
        ],
        "answer": "4",
        "explain": "블록이 없으므로 for는 첫 문장만 반복. i=1,2일 때 AAA 2번. 그 후 BBB 1번 출력.",
    },
    {
        "id": 14,
        "type": "mc",
        "category": "csharp_control",
        "question": 'for(int i=3;i>1;i++) Console.Write("AAA"); → 결과는?',
        "choices": [
            "① AAA AAA AAA",
            "② AAA AAA",
            "③ AAA",
            "④ 아무것도 출력되지 않음",
            "⑤ 무한 반복",
        ],
        "answer": "5",
        "explain": "i가 3에서 시작해 i++로 증가. i는 계속 > 1 이므로 종료 조건을 만족 못 함 → 무한 반복.",
    },
    {
        "id": 15,
        "type": "short",
        "category": "csharp_control",
        "question": "이중 for: 바깥 for(i=1;i<4;i++), 안쪽 for(k=1;k<3;k++)에서 'A'를 찍으면 총 몇 개?",
        "accept": ["6", "6개"],
        "explain": "바깥 3회 × 안쪽 2회 = 6번.",
    },
    {
        "id": 16,
        "type": "short",
        "category": "csharp_control",
        "question": "반복문을 즉시 탈출하는 제어문은? (영단어)",
        "accept": ["break"],
        "explain": "break는 가장 가까운 반복문 또는 switch를 빠져나갑니다.",
    },
    {
        "id": 17,
        "type": "short",
        "category": "csharp_control",
        "question": "반복문의 조건식으로 돌아가는 제어문은? (영단어)",
        "accept": ["continue"],
        "explain": "continue는 이번 반복을 건너뛰고 다음 조건 검사로 이동합니다.",
    },

    # ===== 배열 / 메서드 =====
    {
        "id": 18,
        "type": "mc",
        "category": "csharp_basic",
        "question": "크기 4의 배열을 선언하는 코드로 올바른 것은?",
        "choices": [
            "① int[4] aa = new int[4];",
            "② int aa[] = new int[4];",
            "③ int aa[4] = new int[];",
            "④ int[] aa = new int[4];",
        ],
        "answer": "4",
        "explain": "C#에서 배열은 타입 뒤에 [] 를 붙입니다: int[] aa = new int[4];",
    },
    {
        "id": 19,
        "type": "mc",
        "category": "csharp_basic",
        "question": "크기 4의 배열을 초기화하는 올바른 코드는?",
        "choices": [
            "① int[] aa = new {10,20,30,40};",
            "② int aa[] = {10,20,30,40};",
            "③ int[] aa = {10,20,30,40};",
            "④ int aa = new {10,20,30,40};",
        ],
        "answer": "3",
        "explain": "배열 리터럴로 초기화할 때는 int[] aa = {10,20,30,40}; 형태를 씁니다.",
    },
    {
        "id": 20,
        "type": "mc",
        "category": "csharp_basic",
        "question": "5행 6열 크기의 2차원 배열 선언으로 올바른 것은?",
        "choices": [
            "① int[,] ary = new int[5,6];",
            "② int[5,6] ary = new int[,];",
            "③ int[][] ary = new int[5][6];",
            "④ int[5][6] ary = new int[][];",
        ],
        "answer": "1",
        "explain": "C#의 다차원 배열은 int[,] 형식으로 선언합니다.",
    },
    {
        "id": 21,
        "type": "mc",
        "category": "csharp_basic",
        "question": "문자열의 크기(길이)를 알아내는 코드는?",
        "choices": [
            "① 문자열.Size()",
            "② 문자열.Size",
            "③ 문자열.Length()",
            "④ 문자열.Length",
        ],
        "answer": "4",
        "explain": "C# string의 길이는 Length 프로퍼티(메서드 아님)입니다. 괄호 없이 .Length.",
    },
    {
        "id": 22,
        "type": "mc",
        "category": "csharp_basic",
        "question": "반환할 값이 2개인 메서드에서 반환하는 올바른 방법은?",
        "choices": [
            "① return 100, 200;",
            "② return 100 200;",
            "③ return [100, 200];",
            "④ return new int[] {100, 200};",
        ],
        "answer": "4",
        "explain": "배열이나 튜플로 묶어서 반환해야 합니다. 여러 값을 콤마로 return 할 수 없습니다.",
    },

    # ===== 객체 지향 =====
    {
        "id": 23,
        "type": "mc",
        "category": "csharp_oop",
        "question": "객체 지향과 관련된 설명 중 거리가 먼 것은?",
        "choices": [
            "① 클래스는 객체 지향에서 중요한 개념이다.",
            "② C++, Java 등도 객체 지향을 지원한다.",
            "③ C#은 완전한 객체 지향 언어다.",
            "④ Python은 객체 지향을 지원하지 않는다.",
        ],
        "answer": "4",
        "explain": "Python도 완전한 객체 지향 언어입니다.",
    },
    {
        "id": 24,
        "type": "mc",
        "category": "csharp_oop",
        "question": "Car 클래스의 인스턴스를 올바르게 생성하는 코드는?",
        "choices": [
            "① Car myCar1 = new Car();",
            "② Car myCar1 = Car();",
            "③ Car myCar1; myCar1 = Car();",
            "④ new myCar1 = Car();",
        ],
        "answer": "1",
        "explain": "인스턴스 생성은 new 키워드 + 생성자 호출. Car myCar1 = new Car();",
    },
    {
        "id": 25,
        "type": "mc",
        "category": "csharp_oop",
        "question": "객체의 필드/메서드 사용법으로 올바른 것은?",
        "choices": [
            "① 인스턴스이름.필드이름() 형식",
            "② 인스턴스이름.메서드이름 형식",
            "③ 인스턴스이름:필드이름() 형식",
            "④ 인스턴스이름.필드이름 형식",
        ],
        "answer": "4",
        "explain": "필드는 괄호 없이, 메서드는 괄호를 붙여 호출합니다. car1.speed, car1.UpSpeed().",
    },
    {
        "id": 26,
        "type": "mc",
        "category": "csharp_oop",
        "question": "메서드에 주로 설정하는 액세스 한정자는?",
        "choices": ["① private", "② public", "③ protected", "④ internal"],
        "answer": "2",
        "explain": "외부에서 호출해 쓰라고 만드는 메서드는 보통 public으로 공개합니다.",
    },
    {
        "id": 27,
        "type": "mc",
        "category": "csharp_oop",
        "question": "상속의 영어 단어는?",
        "choices": ["① Succession", "② Heredity", "③ Instance", "④ Inheritance"],
        "answer": "4",
        "explain": "객체 지향에서 상속(Inheritance). : 기호로 부모 클래스를 지정합니다.",
    },
    {
        "id": 28,
        "type": "short",
        "category": "csharp_oop",
        "question": 'Car 생성자 "AAA ", Sedan:Car 생성자 "BBB " 에서 Sedan s1 = new Sedan(); 실행 시 출력은? (공백 포함 그대로)',
        "accept": ["AAA BBB ", "AAA BBB", "aaa bbb"],
        "explain": "파생 클래스 생성 시 부모 생성자가 먼저 호출되어 AAA 출력, 그다음 자식 생성자로 BBB 출력.",
    },
    {
        "id": 29,
        "type": "mc",
        "category": "csharp_oop",
        "question": "필드나 메서드의 상속을 제한하기 위해 사용하는 액세스 한정자는?",
        "choices": ["① public", "② private", "③ protected", "④ internal"],
        "answer": "2",
        "explain": "private으로 선언된 멤버는 파생 클래스에서 접근할 수 없습니다.",
    },
    {
        "id": 30,
        "type": "short",
        "category": "csharp_oop",
        "question": "현재 객체 자기 자신을 참조하는 C# 키워드는?",
        "accept": ["this"],
        "explain": "this는 현재 인스턴스를 가리킵니다. 매개변수와 필드 이름이 겹칠 때 특히 유용합니다.",
    },
    {
        "id": 31,
        "type": "short",
        "category": "csharp_oop",
        "question": "Person p1 = new Person(); p1.age=10; Person p2 = p1; p2.age=20; 이후 p1.age의 값은?",
        "accept": ["20"],
        "explain": "객체는 참조 타입. p2=p1 이면 같은 객체를 가리키므로 p2.age 변경은 p1.age에도 반영됩니다.",
    },
    {
        "id": 32,
        "type": "mc",
        "category": "csharp_oop",
        "question": "C#에서 객체는 어디에 생성되는가?",
        "choices": [
            "① 값 타입으로 스택에 저장",
            "② 레지스터에 저장",
            "③ 힙(heap)에 생성",
            "④ 전역 영역",
        ],
        "answer": "3",
        "explain": "참조 타입인 객체는 힙에 생성되고, 변수는 그 주소(참조)만 보관합니다.",
    },

    # ===== Unity =====
    {
        "id": 33,
        "type": "mc",
        "category": "unity",
        "question": "Unity에서 새로운 프로젝트를 생성할 때 선택하는 것은?",
        "choices": ["A. Scene", "B. Template", "C. Script", "D. Package"],
        "answer": "B",
        "explain": "Unity Hub에서 프로젝트 생성 시 2D/3D/URP 등 Template을 선택합니다.",
    },
    {
        "id": 34,
        "type": "mc",
        "category": "unity",
        "question": "Hierarchy 창의 역할은?",
        "choices": [
            "A. 코드 작성",
            "B. 게임 오브젝트 목록 표시",
            "C. 애니메이션 편집",
            "D. 빌드 설정",
        ],
        "answer": "B",
        "explain": "Hierarchy 창은 현재 씬에 존재하는 게임 오브젝트의 계층 구조를 보여줍니다.",
    },
    {
        "id": 35,
        "type": "mc",
        "category": "unity",
        "question": "GameObject에 컴포넌트를 추가하는 방법은?",
        "choices": [
            "A. Inspector에서 Add Component 클릭",
            "B. Scene에서 드래그",
            "C. Console에서 입력",
            "D. Project 창에서 생성",
        ],
        "answer": "A",
        "explain": "Inspector 창 하단의 Add Component 버튼으로 컴포넌트를 추가합니다.",
    },
    {
        "id": 36,
        "type": "mc",
        "category": "unity",
        "question": "Transform 컴포넌트의 역할은?",
        "choices": [
            "A. 물리 계산",
            "B. 위치·회전·크기 설정",
            "C. 렌더링",
            "D. 사운드 처리",
        ],
        "answer": "B",
        "explain": "Transform은 Position, Rotation, Scale을 다루는 가장 기본 컴포넌트입니다.",
    },
    {
        "id": 37,
        "type": "mc",
        "category": "unity",
        "question": "Prefab이란?",
        "choices": [
            "A. 스크립트 파일",
            "B. 재사용 가능한 오브젝트 템플릿",
            "C. 카메라 설정",
            "D. UI 요소",
        ],
        "answer": "B",
        "explain": "Prefab은 오브젝트를 템플릿화해 여러 씬에서 재사용할 수 있게 해주는 기능입니다.",
    },
    {
        "id": 38,
        "type": "mc",
        "category": "unity",
        "question": "Rigidbody 컴포넌트의 역할은?",
        "choices": [
            "A. UI 구성",
            "B. 물리 효과 적용",
            "C. 카메라 설정",
            "D. 사운드 출력",
        ],
        "answer": "B",
        "explain": "Rigidbody가 붙은 오브젝트는 중력·힘 등 물리 법칙의 영향을 받습니다.",
    },
    {
        "id": 39,
        "type": "mc",
        "category": "unity",
        "question": "Update() 함수가 호출되는 시점은?",
        "choices": [
            "A. 게임 시작 시 1회",
            "B. 매 프레임마다",
            "C. 충돌 시",
            "D. 종료 시",
        ],
        "answer": "B",
        "explain": "Update()는 매 프레임 한 번씩 호출됩니다. 1회 실행은 Start().",
    },
    {
        "id": 40,
        "type": "mc",
        "category": "unity",
        "question": "FixedUpdate()의 용도는?",
        "choices": [
            "A. UI 업데이트",
            "B. 물리 연산",
            "C. 렌더링",
            "D. 사운드 처리",
        ],
        "answer": "B",
        "explain": "FixedUpdate()는 고정된 시간 간격으로 호출되며 Rigidbody 같은 물리 처리에 사용합니다.",
    },
    {
        "id": 41,
        "type": "mc",
        "category": "unity",
        "question": "Instantiate() 함수는 무엇을 하는가?",
        "choices": ["A. 삭제", "B. 복제 생성", "C. 이동", "D. 회전"],
        "answer": "B",
        "explain": "Instantiate()는 Prefab이나 기존 오브젝트의 복제본을 씬에 생성합니다.",
    },
    {
        "id": 42,
        "type": "mc",
        "category": "unity",
        "question": "Start() 함수의 특징은?",
        "choices": [
            "A. 매 프레임 실행",
            "B. 초기 1회 실행",
            "C. 충돌 시 실행",
            "D. 종료 시 실행",
        ],
        "answer": "B",
        "explain": "Start()는 스크립트가 활성화된 후 첫 프레임 직전에 단 한 번 호출됩니다.",
    },
    {
        "id": 43,
        "type": "mc",
        "category": "unity",
        "question": "Coroutine의 특징은?",
        "choices": [
            "A. 병렬 처리",
            "B. 시간 지연 처리",
            "C. 렌더링",
            "D. 입력 처리",
        ],
        "answer": "B",
        "explain": "코루틴은 yield를 이용해 여러 프레임에 걸쳐 실행을 분산하거나 지연시킬 수 있습니다. 병렬(다중 스레드) 아님.",
    },
    {
        "id": 44,
        "type": "mc",
        "category": "unity",
        "question": "Singleton 패턴의 목적은?",
        "choices": [
            "A. 여러 객체 생성",
            "B. 하나의 인스턴스 유지",
            "C. UI 구성",
            "D. 렌더링",
        ],
        "answer": "B",
        "explain": "Singleton은 프로그램 전체에서 단 하나의 인스턴스만 존재하도록 보장하는 패턴입니다.",
    },
    {
        "id": 45,
        "type": "short",
        "category": "unity",
        "question": "Unity에서 위치/회전/크기를 담당하는 컴포넌트 이름은?",
        "accept": ["transform"],
        "explain": "모든 GameObject는 Transform 컴포넌트를 필수로 가집니다.",
    },
    {
        "id": 46,
        "type": "short",
        "category": "unity",
        "question": "Unity에서 UI를 구성하는 기본 시스템(오브젝트)은?",
        "accept": ["canvas"],
        "explain": "모든 UI 요소는 Canvas의 자식으로 배치되어야 화면에 렌더링됩니다.",
    },
]


CATEGORY_NAMES = {
    "csharp_basic": "C# 기초(변수/연산자/배열)",
    "csharp_control": "C# 제어문(if/for/while)",
    "csharp_oop": "C# 객체지향(클래스/상속)",
    "unity": "Unity 기초",
}
